import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app/app-sidebar";
import { MobileNav } from "@/components/app/mobile-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="flex min-h-screen  w-full">
            {/* Sidebar para desktop */}
            <div className="hidden md:block">
              <AppSidebar />
              <SidebarTrigger />
            </div>

            {/* Contenido principal */}
            <main className="flex-1 pb-16 md:pb-0">
              <div className="container mx-auto">
                <Providers>{children}</Providers>
              </div>
            </main>
          </div>

          {/* Navegación móvil */}
          <MobileNav />
        </SidebarProvider>
      </body>
    </html>
  );
}
